### ISSUE TITLE
ci/cd: unit test hangs for a long time intermittently

### ISSUE THREAD

**Issue by rchincha** [anuvu/zot#286]
https://github.com/anuvu/zot/runs/4243958797?check_suite_focus=true

```
coverage: 16.4% of statements in ./...
panic: test timed out after 10m0s

goroutine 1192 [running]:
testing.(*M).startAlarm.func1()
testing/testing.go:1700 +0x11f
created by time.goFunc
time/sleep.go:180 +0x52
```

**Comment by rchincha** [comment]
Another one:
https://github.com/anuvu/zot/runs/4255374734?check_suite_focus=true
